spring:
  application:
    name: lv2-final-mission

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
