spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret-key: X8m6+o7fG1a3Fv+eLhGkzQfW9JvK1qYdO2eR1u4wZxY=

payment:
  key: test-payment-key
  cid: test-cid
